# This pod defines a main application container which writes
# the current date to a log file every five seconds.

# The sidecar container is nginx serving that log file.
# (In practice, your sidecar is likely to be a log collection
# container that uploads to external storage.)

# Once the pod is running: #
# (Connect to the sidecar pod)
# kubectl exec pod-with-sidecar -c sidecar-container -it bash #
# (Install curl on the sidecar)
# apt-get update && apt-get install curl #
# (Access the log file via the sidecar)
# curl 'http://localhost:80/app.txt' 
kind: Pod
apiVersion: v1
metadata:
  name: pod-with-sidecar 
spec:
  # Create a volume called 'shared-logs' that the # app and sidecar share.
  volumes:
  - name: shared-logs
    emptyDir: {}
  # In the sidecar pattern, there is a main application
  # container and a sidecar container. 
  containers:
  # Main application container
  - name: app-container
    # Simple application: write the current date every 5s. 
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/app.txt; sleep 5;done"]
    # Mount the pod's shared log file into the app container.
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
    # Sidecar container
  - name: sidecar-container
    # Simple sidecar: display log files using nginx. 
    image: nginx:1.7.9
    ports:
      - containerPort: 80
    # Mount the pod's shared log file into the sidecar
    # container. In this case, nginx will serve the files
    # in this directory. 
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html